# SPDX-License-Identifier: GPL-2.0
name: CSB on openEuler
on: [workflow_dispatch, push, pull_request]

jobs:
  #
  # Build the image once, reuse it in all later jobs
  #
  build-image:
    name: openeuler-csb image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [ aarch64 ]
    outputs:
      image-ref: ${{ steps.build.outputs.image }}

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v5
        with:
          context: .
          file: .github/workflows/openeuler/Dockerfile
          tags: ghcr.io/${{ github.repository_owner }}/openeuler-csb:${{ matrix.arch }}
          push: true
          # openEuler Image to use: 24.03-SP3 LTS
          build-args:
            BASE_IMAGE=openeuler/openeuler:24.03-lts-sp3

  #
  # Run tests on openEuler via openeuler-csb image
  #
  openEuler:
    name: OpenEuler Tests
    needs: build-image
    runs-on: ubuntu-latest
    env:
      LC_ALL: en_US.utf8
      LANG: en_US.utf8
    strategy:
      fail-fast: false
      matrix:
        arch: [ aarch64 ]
        test: [ bm_empty ]

    container:
      image: ghcr.io/${{ github.repository_owner }}/openeuler-csb:${{ matrix.arch }}
      volumes:
        # share the repo itself
        - ${{ github.workspace }}:/root/csb

        # Share Linux kernel
        - /boot:/boot
        - /lib/modules:/lib/modules

        # Allow running sub-containers
        - /var/run/docker.sock:/var/run/docker.sock

    steps:
      - name: Test ${{ matrix.test }}
        run: cd /root/csb && scripts/fg-diff/run-single.sh config/${{ matrix.test }}.json
