# SPDX-License-Identifier: MIT
name: Build openEuler CSB
on: [workflow_dispatch]

permissions:
  contents: read
  packages: write

jobs:
  #
  # Build the image once, reuse it in all later jobs
  #
  build-image:
    name: openeuler-csb image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - name: Log in to github
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push openeuler-csb
        uses: docker/build-push-action@v6
        with:
          context: .
          file: .github/workflows/openeuler/Dockerfile
          tags: ghcr.io/${{ github.repository_owner}}/csb/openeuler-csb:latest
          push: true
          platforms: linux/amd64
